Add `--exclude` to pkgmt `format` and pkgmt `lint`
ploomber/pkgmt pull request #62
Opened 2023-06-28 18:44 UTC by mehtamohit013

Closes #55

2023-06-28 22:02 UTC, tonykploomber commented
Is this ready for review?

2023-06-29 06:40 UTC, mehtamohit013 commented
It is still WIP

2023-06-30 12:49 UTC, mehtamohit013 commented
@edublancas @tonykploomber 
Ready for review

2023-06-30 14:37 UTC, edublancas requested changes
tested it and it works well. just minor comments

2023-06-30 14:37 UTC, edublancas commented on src/pkgmt/formatting.py
> +    print("Running command:", " ".join(map(quote, cmd)))
please change from print -> click.echo

2023-06-30 14:37 UTC, edublancas commented on src/pkgmt/formatting.py
> +    print("Running command:", " ".join(map(quote, cmd)))
(all other instances as well)

2023-06-30 14:37 UTC, edublancas commented on tests/test_cli.py
>      result_1 = runner.invoke(cli.cli, ["lint", "tmp_folder1"])
use pytest.mark.parametrize to test each case separately

2023-06-30 15:26 UTC, mehtamohit013 commented
@edublancas 
Ready for merge

2023-06-30 15:28 UTC, edublancas approved these changes

2023-06-30 15:28 UTC, merged